[package]
name = "onlytax-ws"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
dotenv = "0.15.0"
env_logger = "0.11.3"
envconfig = "0.10.0"
eyre = "0.6.12"
log = "0.4.22"
socketioxide = { version = "0.13.1", features = ["state", "extensions"] }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["cors", "fs"] }
